/*
  Catálogos Área → Sección → Maquinaria
  Fuente: hoja 'hoja concat' de libro DatasCOPE.xlsx.
  Registros importados: 281.
*/
USE [ReportesMantencion];
GO
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.Areas', N'U') IS NULL
BEGIN
    EXEC(N'CREATE TABLE dbo.Areas (
        AreaId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        Nombre NVARCHAR(300) NOT NULL,
        Activo BIT NOT NULL DEFAULT (1),
        CreadoEn DATETIMEOFFSET(7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
        UNIQUE (Nombre)
    )');
END;
GO

IF OBJECT_ID(N'dbo.Secciones', N'U') IS NULL
BEGIN
    EXEC(N'CREATE TABLE dbo.Secciones (
        SeccionId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        AreaId INT NOT NULL REFERENCES dbo.Areas(AreaId),
        Nombre NVARCHAR(300) NOT NULL,
        Activo BIT NOT NULL DEFAULT (1),
        CreadoEn DATETIMEOFFSET(7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
        UNIQUE (AreaId, Nombre)
    )');
END;
GO

IF OBJECT_ID(N'dbo.Maquinarias', N'U') IS NULL
BEGIN
    EXEC(N'CREATE TABLE dbo.Maquinarias (
        MaquinariaId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        SeccionId INT NOT NULL REFERENCES dbo.Secciones(SeccionId),
        CodigoOrigen INT NULL,
        Nombre NVARCHAR(500) NOT NULL,
        Activo BIT NOT NULL DEFAULT (1),
        CreadoEn DATETIMEOFFSET(7) NOT NULL DEFAULT (SYSDATETIMEOFFSET())
    )');
END;
GO

/* Compatibilidad con una ejecución anterior de este script que exigía código
   y nombre únicos. La fuente contiene dos códigos vacíos y nombres repetidos. */
IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'UQ_Maquinarias_CodigoOrigen' AND parent_object_id = OBJECT_ID(N'dbo.Maquinarias'))
    ALTER TABLE dbo.Maquinarias DROP CONSTRAINT UQ_Maquinarias_CodigoOrigen;
IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'UQ_Maquinarias_Seccion_Nombre' AND parent_object_id = OBJECT_ID(N'dbo.Maquinarias'))
    ALTER TABLE dbo.Maquinarias DROP CONSTRAINT UQ_Maquinarias_Seccion_Nombre;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Maquinarias_CodigoOrigen' AND object_id = OBJECT_ID(N'dbo.Maquinarias'))
    DROP INDEX UX_Maquinarias_CodigoOrigen ON dbo.Maquinarias;
IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.Maquinarias') AND name = N'CodigoOrigen' AND is_nullable = 0
)
    ALTER TABLE dbo.Maquinarias ALTER COLUMN CodigoOrigen INT NULL;
GO

BEGIN TRANSACTION;
DECLARE @Fuente TABLE (
    CodigoOrigen INT NULL,
    AreaNombre NVARCHAR(300) NOT NULL,
    SeccionNombre NVARCHAR(300) NOT NULL,
    MaquinariaNombre NVARCHAR(500) NOT NULL
);
INSERT INTO @Fuente (CodigoOrigen, AreaNombre, SeccionNombre, MaquinariaNombre)
VALUES
        (1, N'PLANTA GENERAL', N'GENERAL', N'COMPRESOR KAESER (CADA 2000 HRS)'),
        (2, N'PLANTA GENERAL', N'GENERAL', N'COMPRESOR SCR AZUL'),
        (3, N'PLANTA GENERAL', N'GENERAL', N'BOMBA POZO AGUA'),
        (4, N'PLANTA GENERAL', N'GENERAL', N'ROMANA CAMIONES'),
        (5, N'PLANTA GENERAL', N'GENERAL', N'TRANSFORMADOR N°1  ELECTRICIDAD PLANTA 500 KVA'),
        (6, N'PLANTA GENERAL', N'GENERAL', N'TRANSFORMADOR N°2 ELECTRICIDAD PLANTA 500 KVA'),
        (7, N'PLANTA GENERAL', N'GENERAL', N'ESTANQUES ALIMENTACION AGUA PLANTA'),
        (8, N'PLANTA GENERAL', N'GENERAL', N'GENERADOR 1 500KVA'),
        (9, N'PLANTA GENERAL', N'GENERAL', N'GENERADOR 2 500KVA'),
        (10, N'PLANTA GENERAL', N'GENERAL', N'PANELES SOLARES'),
        (11, N'PLANTA GENERAL', N'GENERAL', N'OTROS'),
        (12, N'MALTA', N'RECEPCION DE CEBADA', N'ELEVADOR 1'),
        (13, N'MALTA', N'RECEPCION DE CEBADA', N'ELEVADOR 3'),
        (14, N'MALTA', N'RECEPCION DE CEBADA', N'TRANSPORTADOR DE CADENA REDLER 1'),
        (15, N'MALTA', N'RECEPCION DE CEBADA', N'ELEVADOR 5'),
        (16, N'MALTA', N'RECEPCION DE CEBADA', N'ELEVADOR 10'),
        (17, N'MALTA', N'RECEPCION DE CEBADA', N'TRANSPORTADOR DE CADENA REDLER SUPERIOR SILOS NUEVOS'),
        (18, N'MALTA', N'RECEPCION DE CEBADA', N'VENTILADOR 1 SILOS'),
        (19, N'MALTA', N'RECEPCION DE CEBADA', N'VENTILADOR 2 SILOS'),
        (20, N'MALTA', N'RECEPCION DE CEBADA', N'DESENBOLSADORA'),
        (21, N'MALTA', N'RECEPCION DE CEBADA', N'FILTRO TRASPASO DE CEBADA (LOZA)'),
        (22, N'MALTA', N'RECEPCION DE CEBADA', N'TORNILLO 2'),
        (23, N'MALTA', N'RECEPCION DE CEBADA', N'EDIFICIO'),
        (24, N'MALTA', N'RECEPCION DE CEBADA', N'OTROS'),
        (25, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'TRANSPORTADOR DE TORNILLO SILOS DE CEBADA'),
        (26, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'ELEVADOR 10'),
        (27, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'CAMBIO PLANETARIO'),
        (28, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'ZARANDA BULLER'),
        (29, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'FILTRO DE MANGAS'),
        (30, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'ESCLUSA DE POLVO'),
        (31, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'ROMANA DE PRODUCCION'),
        (32, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'ELEVADOR 7'),
        (33, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'TRANSPORTADOR DE TORNILLO AEREO LARGO'),
        (34, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'TRANSPORTADOR DE TORNILLO INVERSOR SILOS KEPLER'),
        (35, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'FILTRO LIMPIEZA DE CEBADA (4TO PISO)'),
        (36, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'EDIFICIO'),
        (37, N'MALTA', N'LIMPIEZA DE CEBADA (PRODUCCION)', N'OTROS'),
        (38, N'MALTA', N'REMOJO', N'TRANSPORTADOR DE TORNILLO CARGA TINAS SILO 61-62'),
        (39, N'MALTA', N'REMOJO', N'TRANSPORTADOR DE TORNILLO CARGA TINAS SILO 63'),
        (40, N'MALTA', N'REMOJO', N'ELEVADOR REMOJO'),
        (41, N'MALTA', N'REMOJO', N'TINA - 1'),
        (42, N'MALTA', N'REMOJO', N'TINA - 2'),
        (43, N'MALTA', N'REMOJO', N'TINA - 3'),
        (44, N'MALTA', N'REMOJO', N'SOPLADOR TINA 1-2'),
        (45, N'MALTA', N'REMOJO', N'SOPLADOR TINA 3'),
        (46, N'MALTA', N'REMOJO', N'EXTRACTOR DE CO2 TINA 1'),
        (47, N'MALTA', N'REMOJO', N'EXTRACTOR DE CO2 TINA 2'),
        (48, N'MALTA', N'REMOJO', N'EXTRACTOR DE CO2 TINA 3'),
        (49, N'MALTA', N'REMOJO', N'BOMBA DE EMPUJE'),
        (50, N'MALTA', N'REMOJO', N'BOMBA BOMBEO'),
        (51, N'MALTA', N'REMOJO', N'BOMBA DE RIEGO'),
        (52, N'MALTA', N'REMOJO', N'EDIFICIO'),
        (53, N'MALTA', N'REMOJO', N'OTROS'),
        (54, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 1'),
        (55, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 2'),
        (56, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 3'),
        (57, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 4'),
        (58, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 5'),
        (59, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 6'),
        (60, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA REVOLVEDORA 7'),
        (61, N'MALTA', N'GERMINACIÓN ANTIGUA', N'CARRO MAQUINA CARGA PALA'),
        (62, N'MALTA', N'GERMINACIÓN ANTIGUA', N'MAQUINA CARGA PALA'),
        (63, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 1'),
        (64, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 2'),
        (65, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 3'),
        (66, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 4'),
        (67, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 5'),
        (68, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 6'),
        (69, N'MALTA', N'GERMINACIÓN ANTIGUA', N'VENTILADOR 7'),
        (70, N'MALTA', N'GERMINACIÓN ANTIGUA', N'HIDROLAVADORA'),
        (71, N'MALTA', N'GERMINACIÓN ANTIGUA', N'BOMBA RIEGO CAJONES'),
        (72, N'MALTA', N'GERMINACIÓN ANTIGUA', N'BOMBA ASPERSORES BAJO CAJON'),
        (73, N'MALTA', N'GERMINACIÓN ANTIGUA', N'EDIFICIO'),
        (74, N'MALTA', N'GERMINACIÓN ANTIGUA', N'OTROS'),
        (75, N'MALTA', N'GERMINACIÓN NUEVA', N'MAQUINA 8'),
        (76, N'MALTA', N'GERMINACIÓN NUEVA', N'MAQUINA 9'),
        (77, N'MALTA', N'GERMINACIÓN NUEVA', N'MAQUINA 10'),
        (78, N'MALTA', N'GERMINACIÓN NUEVA', N'VENTILADOR 8'),
        (79, N'MALTA', N'GERMINACIÓN NUEVA', N'VENTILADOR 9'),
        (80, N'MALTA', N'GERMINACIÓN NUEVA', N'VENTILADOR 10'),
        (81, N'MALTA', N'GERMINACIÓN NUEVA', N'PARED MOVIL 8'),
        (82, N'MALTA', N'GERMINACIÓN NUEVA', N'PARED MOVIL 9'),
        (83, N'MALTA', N'GERMINACIÓN NUEVA', N'PARED MOVIL 10'),
        (84, N'MALTA', N'GERMINACIÓN NUEVA', N'HIDROLAVADORA'),
        (85, N'MALTA', N'GERMINACIÓN NUEVA', N'BOMBA DE AGUA RIEGO CAJONES'),
        (86, N'MALTA', N'GERMINACIÓN NUEVA', N'BOMBA DE AGUA ASPERSORES BAJO CAJON'),
        (87, N'MALTA', N'GERMINACIÓN NUEVA', N'ABLANDADOR DE AGUA'),
        (88, N'MALTA', N'GERMINACIÓN NUEVA', N'EDIFICIO'),
        (89, N'MALTA', N'GERMINACIÓN NUEVA', N'OTROS'),
        (90, N'MALTA', N'HORNO MIAG', N'VENTILADOR'),
        (91, N'MALTA', N'HORNO MIAG', N'CARDAN'),
        (92, N'MALTA', N'HORNO MIAG', N'MOTOR'),
        (93, N'MALTA', N'HORNO MIAG', N'SISTEMA HIDRAULICO'),
        (94, N'MALTA', N'HORNO MIAG', N'TELA HORNO'),
        (95, N'MALTA', N'HORNO MIAG', N'QUEMADOR'),
        (96, N'MALTA', N'HORNO MIAG', N'CELOSIAS'),
        (97, N'MALTA', N'HORNO MIAG', N'TRANSPORTADOR DE BANDA CINTA MIAG'),
        (98, N'MALTA', N'HORNO MIAG', N'ELEVADOR DE MALTA VERDE'),
        (99, N'MALTA', N'HORNO MIAG', N'TRANSPORTADOR DE TORNILLO SOBRE LOZA'),
        (100, N'MALTA', N'HORNO MIAG', N'TRANSPORTADOR DE TORNILLO SUPERIOR  CARGA'),
        (101, N'MALTA', N'HORNO MIAG', N'TRANSPORTADOR DE TORNILLO INFERIOR CARGA'),
        (102, N'MALTA', N'HORNO MIAG', N'TRANSPORTADOR DE CADENA REDLER PAVO'),
        (103, N'MALTA', N'HORNO MIAG', N'ELEVADOR 15'),
        (104, N'MALTA', N'HORNO MIAG', N'EDIFICIO'),
        (105, N'MALTA', N'HORNO MIAG', N'OTROS'),
        (106, N'MALTA', N'HORNO SEGINSA', N'VENTILADORES'),
        (107, N'MALTA', N'HORNO SEGINSA', N'MOTORES VENTILADORES'),
        (108, N'MALTA', N'HORNO SEGINSA', N'MOTORES GIRO TELA'),
        (109, N'MALTA', N'HORNO SEGINSA', N'TELA HORNO'),
        (110, N'MALTA', N'HORNO SEGINSA', N'QUEMADOR'),
        (111, N'MALTA', N'HORNO SEGINSA', N'CELOSIAS'),
        (112, N'MALTA', N'HORNO SEGINSA', N'TRANSPORTADOR DE BANDA CINTA SEGINSA'),
        (113, N'MALTA', N'HORNO SEGINSA', N'ELEVADOR MALTA VERDE'),
        (114, N'MALTA', N'HORNO SEGINSA', N'TRANSPORTADOR DE TORNILLO SOBRE HORNO'),
        (115, N'MALTA', N'HORNO SEGINSA', N'TRANSPORTADOR DE TORNILLO INTERIOR CARGA'),
        (116, N'MALTA', N'HORNO SEGINSA', N'COMPUERTA DESCARGA HORNO'),
        (117, N'MALTA', N'HORNO SEGINSA', N'TRANSPORTADOR DE CADENA REDLER DESCARGA'),
        (118, N'MALTA', N'HORNO SEGINSA', N'EDIFICIO'),
        (119, N'MALTA', N'HORNO SEGINSA', N'OTROS'),
        (120, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE CADENA REDLER SILOS ANALISIS'),
        (121, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ELEVADOR 11'),
        (122, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE CADENA REDLER AEREO'),
        (123, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE TORNILLO DIAGONAL'),
        (124, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'DESBROTADORA 1'),
        (125, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'DESBROTADORA 2'),
        (126, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'DESBROTADORA 3'),
        (127, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ZARANDA 1'),
        (128, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ZARANDA 2'),
        (129, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE TORNILLO RECIBIDOR'),
        (130, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ELEVADOR 6'),
        (131, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ROMANA PULIDO'),
        (132, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'ELEVADOR 9'),
        (133, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE TORNILLO 3'),
        (134, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'TRANSPORTADOR DE TORNILLO 4'),
        (135, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'FILTRO POLVO LOSA'),
        (136, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'FILTRO LIMPIEZA DE MALTA PULIDO'),
        (137, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'EDIFICIO'),
        (138, N'MALTA', N'LIMPIEZA DE MALTA (PULIDO)', N'OTROS'),
        (139, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 1'),
        (140, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 2'),
        (141, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 3'),
        (142, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 4'),
        (143, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 5'),
        (144, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO 6'),
        (145, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 21'),
        (146, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 22'),
        (147, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 23'),
        (148, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE CADENA REDLER DESPACHO'),
        (149, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO CORTO'),
        (150, N'MALTA', N'DESPACHO', N'ELEVADOR 8'),
        (151, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 51'),
        (152, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 52'),
        (153, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 53'),
        (154, N'MALTA', N'DESPACHO', N'TRANSPORTADOR DE TORNILLO SILO 54'),
        (155, N'MALTA', N'DESPACHO', N'ELEVADOR 12'),
        (156, N'MALTA', N'DESPACHO', N'ZARANDA GRANEL'),
        (157, N'MALTA', N'DESPACHO', N'ZARANDA A SACOS'),
        (158, N'MALTA', N'DESPACHO', N'SISTEMA DE ENVASADO'),
        (159, N'MALTA', N'DESPACHO', N'FILTRO TRANSPORTE DE MALTA DESPACHO (NARANJO)'),
        (160, N'MALTA', N'DESPACHO', N'FILTRO ZARANDA DESPACHO GRANEL (LADO BODEGA SUBPRODUCTO)'),
        (161, N'MALTA', N'DESPACHO', N'FILTRO ZARANDA DESPACHO SACOS (VERDE)'),
        (162, N'MALTA', N'DESPACHO', N'EDIFICIO'),
        (163, N'MALTA', N'DESPACHO', N'OTROS'),
        (164, N'MOLINO', N'MOLINO HARINA', N'ABLANDADOR DE AGUA'),
        (165, N'MOLINO', N'MOLINO HARINA', N'SOPLADOR (SILOS AMARILLOS)'),
        (166, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA 1 EXTERIOR SILOS AMARILLO'),
        (167, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA 2 EXTERIOR SILOS AMARILLO'),
        (168, N'MOLINO', N'MOLINO HARINA', N'VALVULA 3 VIAS'),
        (169, N'MOLINO', N'MOLINO HARINA', N'BOMBA HUMECTANTE'),
        (170, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA REMOJO'),
        (171, N'MOLINO', N'MOLINO HARINA', N'ROSCO CORTO REMOJO'),
        (172, N'MOLINO', N'MOLINO HARINA', N'ELEVADOR DE REMOJO'),
        (173, N'MOLINO', N'MOLINO HARINA', N'ROSCO CORTO SUPERIOR SILOS AMARILLOS'),
        (174, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA 1 SILO AMARILLO'),
        (175, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA 2 SILO AMARILLO'),
        (176, N'MOLINO', N'MOLINO HARINA', N'ROSCO CANOA T1'),
        (177, N'MOLINO', N'MOLINO HARINA', N'BANCO DE MOLIENDA T1'),
        (178, N'MOLINO', N'MOLINO HARINA', N'BANCO DE MOLIENDA T2'),
        (179, N'MOLINO', N'MOLINO HARINA', N'BANCO DE MOLIENDA C1'),
        (180, N'MOLINO', N'MOLINO HARINA', N'BANCO DE MOLIENDA C2'),
        (181, N'MOLINO', N'MOLINO HARINA', N'ROSCO CANOA C1'),
        (182, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA T1'),
        (183, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA T2'),
        (184, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA C1'),
        (185, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA C2'),
        (186, N'MOLINO', N'MOLINO HARINA', N'DISGREGADOR C1-C2'),
        (187, N'MOLINO', N'MOLINO HARINA', N'CERNIDORES T1-T2'),
        (188, N'MOLINO', N'MOLINO HARINA', N'CERNIDORES C1-C2'),
        (189, N'MOLINO', N'MOLINO HARINA', N'ESCLUSA RECUPERADORA'),
        (190, N'MOLINO', N'MOLINO HARINA', N'RECUPERADORA'),
        (191, N'MOLINO', N'MOLINO HARINA', N'TURBO TAMIZ'),
        (192, N'MOLINO', N'MOLINO HARINA', N'ROSCO CANOA HARINA'),
        (193, N'MOLINO', N'MOLINO HARINA', N'ROMPE HUEVO'),
        (194, N'MOLINO', N'MOLINO HARINA', N'FILTRO DE HARINA'),
        (195, N'MOLINO', N'MOLINO HARINA', N'EDIFICIO'),
        (196, N'MOLINO', N'MOLINO HARINA', N'OTROS'),
        (197, N'MOLINO', N'MOLINO PERLADO', N'DOSIFICADOR DE TOLVA'),
        (198, N'MOLINO', N'MOLINO PERLADO', N'DESPIEDRADORA'),
        (199, N'MOLINO', N'MOLINO PERLADO', N'ROSCO CANOA 1'),
        (200, N'MOLINO', N'MOLINO PERLADO', N'ELEVADOR 1'),
        (201, N'MOLINO', N'MOLINO PERLADO', N'DOSIFICADOR HACIA ELEVADOR'),
        (202, N'MOLINO', N'MOLINO PERLADO', N'ELEVADOR 2 MOLINO'),
        (203, N'MOLINO', N'MOLINO PERLADO', N'PERLADORA 1'),
        (204, N'MOLINO', N'MOLINO PERLADO', N'TRIUER'),
        (205, N'MOLINO', N'MOLINO PERLADO', N'ELEVADOR 3'),
        (206, N'MOLINO', N'MOLINO PERLADO', N'PERLADORA 2'),
        (207, N'MOLINO', N'MOLINO PERLADO', N'PERLADORA 3'),
        (208, N'MOLINO', N'MOLINO PERLADO', N'ELEVADOR 5'),
        (209, N'MOLINO', N'MOLINO PERLADO', N'ZARANDA'),
        (210, N'MOLINO', N'MOLINO PERLADO', N'FILTRO DESPIEDRADORA'),
        (211, N'MOLINO', N'MOLINO PERLADO', N'FILTRO PERLADO'),
        (212, N'MOLINO', N'MOLINO PERLADO', N'EDIFICIO'),
        (213, N'MOLINO', N'MOLINO PERLADO', N'OTROS'),
        (214, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ABLANDADOR DE AGUA'),
        (215, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'SOPLADOR'),
        (NULL, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ESCLUSA'),
        (216, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO TOLVA MALTA VERDE CARGA TOSTADORAS'),
        (217, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ELEVADOR MALTA VERDE CARGA TOSTADORAS'),
        (218, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO CORTO AEREO CARGA TOSTADORAS'),
        (219, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO LARGO CARGA TOSTADORAS'),
        (220, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'TOSTADORA 1'),
        (221, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'TOSTADORA 2'),
        (222, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'QUEMADOR TOSTADORA 1'),
        (223, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'QUEMADOR TOSTADORA 2'),
        (224, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO DESCARGA TOSTADORAS'),
        (225, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ELEVADOR DESCARGA TOSTADORAS'),
        (226, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO AEREO DESCARGA TOSTADORAS'),
        (227, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO 1 ENVASADO PAVOS'),
        (228, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ROSCO 2 ENVASADO PAVOS'),
        (229, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ELEVADOR ENVASADO'),
        (230, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'ZARANDA'),
        (231, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'FILTRO DE LIMPIEZA MALTAS ESPECIALES'),
        (232, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'EDIFICIO'),
        (233, N'MALTAS ESPECIALES', N'MALTAS ESPECIALES', N'OTROS'),
        (234, N'RILES', N'RILES', N'TECLE ELECTRICO POZO'),
        (235, N'RILES', N'RILES', N'BOMBA POZO 1'),
        (236, N'RILES', N'RILES', N'BOMBA POZO 2'),
        (237, N'RILES', N'RILES', N'FILTRO PARABOLICO'),
        (238, N'RILES', N'RILES', N'FILTRO ROTATORIO'),
        (239, N'RILES', N'RILES', N'AIREADOR 1 PISCINA 1'),
        (240, N'RILES', N'RILES', N'AIREADOR 2 PISCINA 1'),
        (241, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 1'),
        (242, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 2'),
        (243, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 3'),
        (244, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 4'),
        (245, N'RILES', N'RILES', N'AIREADOR 1 PISCINA 2'),
        (246, N'RILES', N'RILES', N'AIREADOR 2 PISCINA 2'),
        (247, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 1'),
        (248, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 2'),
        (249, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 3'),
        (250, N'RILES', N'RILES', N'SOPLADOR SUMERGIBLE 4'),
        (251, N'RILES', N'RILES', N'BOMBA 1 PISCINA 3'),
        (252, N'RILES', N'RILES', N'BOMBA 2 PISCINA 3'),
        (253, N'RILES', N'RILES', N'SENSOR CAUDAL PISCINA 3'),
        (254, N'RILES', N'RILES', N'SOPLADOR LADO OESTE PISCINA 1-2'),
        (255, N'RILES', N'RILES', N'SOPLADOR LADO ESTE PISCINA 1-2'),
        (256, N'RILES', N'RILES', N'COMPRESOR DE AIRE KAESER'),
        (257, N'RILES', N'RILES', N'SOPLADOR DE ESTANQUE 1'),
        (258, N'RILES', N'RILES', N'SOPLADOR DE ESTANQUE 2'),
        (259, N'RILES', N'RILES', N'DECANTER'),
        (260, N'RILES', N'RILES', N'EDIFICIO'),
        (261, N'RILES', N'RILES', N'OTROS'),
        (262, N'MALTA', N'SISTEMA DE FRIOS', N'ABLANDADOR DE AGUA'),
        (263, N'MALTA', N'SISTEMA DE FRIOS', N'BOMBA DE BOMBEO'),
        (264, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 1'),
        (265, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 2'),
        (266, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 3'),
        (267, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 4'),
        (268, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 5'),
        (269, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 6'),
        (270, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 7'),
        (271, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 8'),
        (272, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 9'),
        (273, N'MALTA', N'SISTEMA DE FRIOS', N'VALVULAS DE EVAPORADOR CAJON 10'),
        (274, N'MALTA', N'SISTEMA DE FRIOS', N'COMPRESOR DE AMONIACO 6A'),
        (275, N'MALTA', N'SISTEMA DE FRIOS', N'COMPRESOR DE AMONIACO 6L'),
        (276, N'MALTA', N'SISTEMA DE FRIOS', N'CONDENSADOR 1'),
        (277, N'MALTA', N'SISTEMA DE FRIOS', N'CONDENSADOR 2'),
        (NULL, N'MALTA', N'SISTEMA DE FRIOS', N'CONDENSADOR 3'),
        (278, N'MALTA', N'SISTEMA DE FRIOS', N'EDIFICIO'),
        (279, N'MALTA', N'SISTEMA DE FRIOS', N'OTROS');

INSERT INTO dbo.Areas (Nombre)
SELECT DISTINCT f.AreaNombre
FROM @Fuente AS f
WHERE NOT EXISTS (SELECT 1 FROM dbo.Areas AS a WHERE a.Nombre = f.AreaNombre);

INSERT INTO dbo.Secciones (AreaId, Nombre)
SELECT DISTINCT a.AreaId, f.SeccionNombre
FROM @Fuente AS f
INNER JOIN dbo.Areas AS a ON a.Nombre = f.AreaNombre
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.Secciones AS s
    WHERE s.AreaId = a.AreaId AND s.Nombre = f.SeccionNombre
);

INSERT INTO dbo.Maquinarias (SeccionId, CodigoOrigen, Nombre)
SELECT s.SeccionId, f.CodigoOrigen, f.MaquinariaNombre
FROM @Fuente AS f
INNER JOIN dbo.Areas AS a ON a.Nombre = f.AreaNombre
INNER JOIN dbo.Secciones AS s ON s.AreaId = a.AreaId AND s.Nombre = f.SeccionNombre
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.Maquinarias AS m
    WHERE (m.CodigoOrigen = f.CodigoOrigen)
       OR (m.CodigoOrigen IS NULL AND f.CodigoOrigen IS NULL AND m.Nombre = f.MaquinariaNombre AND m.SeccionId = s.SeccionId)
);
COMMIT TRANSACTION;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Maquinarias_CodigoOrigen' AND object_id = OBJECT_ID(N'dbo.Maquinarias'))
    CREATE UNIQUE INDEX UX_Maquinarias_CodigoOrigen ON dbo.Maquinarias(CodigoOrigen) WHERE CodigoOrigen IS NOT NULL;
GO

CREATE OR ALTER VIEW dbo.vw_AreaSeccionMaquinaria
AS
SELECT
    a.AreaId,
    a.Nombre AS Area,
    s.SeccionId,
    s.Nombre AS Seccion,
    m.MaquinariaId,
    m.CodigoOrigen,
    m.Nombre AS Maquinaria,
    a.Activo AS AreaActiva,
    s.Activo AS SeccionActiva,
    m.Activo AS MaquinariaActiva
FROM dbo.Areas AS a
INNER JOIN dbo.Secciones AS s ON s.AreaId = a.AreaId
INNER JOIN dbo.Maquinarias AS m ON m.SeccionId = s.SeccionId;
GO

SELECT * FROM dbo.vw_AreaSeccionMaquinaria ORDER BY Area, Seccion, Maquinaria;
GO
